//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheekiBreeki.CMH.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BONO
    {
        public BONO()
        {
            this.PAGO = new HashSet<PAGO>();
        }
    
        public int ID_BONO { get; set; }
        public Nullable<int> CANT_BONO { get; set; }
        public string COD_ASEGURADORA { get; set; }
        public Nullable<int> ID_ASEGURADORA { get; set; }
    
        public virtual ASEGURADORA ASEGURADORA { get; set; }
        public virtual ICollection<PAGO> PAGO { get; set; }
    }
}
