//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheekiBreeki.CMH.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAJA
    {
        public CAJA()
        {
            this.PAGO = new HashSet<PAGO>();
        }
    
        public int ID_CAJA { get; set; }
        public Nullable<System.DateTime> FEC_HORA_CIERRE { get; set; }
        public Nullable<System.DateTime> FEC_HORA_APERTURA { get; set; }
        public Nullable<int> ID_FUNCIONARIO { get; set; }
    
        public virtual ICollection<PAGO> PAGO { get; set; }
        public virtual FUNCIONARIO FUNCIONARIO { get; set; }
    }
}
