//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheekiBreeki.CMH.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ARCHIVO> ARCHIVO { get; set; }
        public DbSet<ASEGURADORA> ASEGURADORA { get; set; }
        public DbSet<ATENCION_AGEN> ATENCION_AGEN { get; set; }
        public DbSet<BONO> BONO { get; set; }
        public DbSet<CAJA> CAJA { get; set; }
        public DbSet<CARGO> CARGO { get; set; }
        public DbSet<DEVOLUCION> DEVOLUCION { get; set; }
        public DbSet<ENTRADA_FICHA> ENTRADA_FICHA { get; set; }
        public DbSet<EQUIPO_REQ> EQUIPO_REQ { get; set; }
        public DbSet<ESPECIALIDAD> ESPECIALIDAD { get; set; }
        public DbSet<ESTADO_ATEN> ESTADO_ATEN { get; set; }
        public DbSet<FICHA> FICHA { get; set; }
        public DbSet<FUNCIONARIO> FUNCIONARIO { get; set; }
        public DbSet<INVENTARIO> INVENTARIO { get; set; }
        public DbSet<ORDEN_ANALISIS> ORDEN_ANALISIS { get; set; }
        public DbSet<PACIENTE> PACIENTE { get; set; }
        public DbSet<PAGO> PAGO { get; set; }
        public DbSet<PERS_MEDICO> PERS_MEDICO { get; set; }
        public DbSet<PERSONAL> PERSONAL { get; set; }
        public DbSet<PRESTACION> PRESTACION { get; set; }
        public DbSet<RES_ATENCION> RES_ATENCION { get; set; }
        public DbSet<TIPO_EQUIPO> TIPO_EQUIPO { get; set; }
        public DbSet<TIPO_PRES> TIPO_PRES { get; set; }
        public DbSet<TURNO> TURNO { get; set; }
    }
}
