//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheekiBreeki.CMH.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTARIO
    {
        public int ID_INVENTARIO_EQUIPO { get; set; }
        public Nullable<int> CANT_BODEGA { get; set; }
        public Nullable<int> ID_TIPO_EQUIPO { get; set; }
    
        public virtual TIPO_EQUIPO TIPO_EQUIPO { get; set; }
    }
}
