INSERT INTO T_EMPRESA (NOMBRE) VALUES ('Compañias de Seguros');
INSERT INTO T_EMPRESA (NOMBRE) VALUES ('Instituciones Mutualistas');

INSERT INTO EMPRESA (NOMBRE,ID_T_EMPRESA) VALUES ('Banmedica',1);
INSERT INTO EMPRESA (NOMBRE,ID_T_EMPRESA) VALUES ('Colmena Golden Cross',1);
INSERT INTO EMPRESA (NOMBRE,ID_T_EMPRESA) VALUES ('Mas vida',2);
INSERT INTO EMPRESA (NOMBRE,ID_T_EMPRESA) VALUES ('Vida tres',2);
INSERT INTO EMPRESA (NOMBRE,ID_T_EMPRESA) VALUES ('Cruz Blanca',1);
INSERT INTO EMPRESA (NOMBRE,ID_T_EMPRESA) VALUES ('Consalud',2);
INSERT INTO EMPRESA (NOMBRE,ID_T_EMPRESA) VALUES ('Ferrosalud',1);

INSERT INTO PLAN (NOMBRE,ID_EMPRESA) VALUES ('Judah',1);
INSERT INTO PLAN (NOMBRE,ID_EMPRESA) VALUES ('Angela',2);
INSERT INTO PLAN (NOMBRE,ID_EMPRESA) VALUES ('Sydney',3);
INSERT INTO PLAN (NOMBRE,ID_EMPRESA) VALUES ('Aidan',4);
INSERT INTO PLAN (NOMBRE,ID_EMPRESA) VALUES ('Tiger',5);

INSERT INTO AFILIADO (RUT,VERIFICADOR,ID_PLAN) VALUES ('17653653','2',1);
INSERT INTO AFILIADO (RUT,VERIFICADOR,ID_PLAN) VALUES ('14040855','9',2);
INSERT INTO AFILIADO (RUT,VERIFICADOR,ID_PLAN) VALUES ('1216879','8',3);
INSERT INTO AFILIADO (RUT,VERIFICADOR,ID_PLAN) VALUES ('16034708','K',4);
INSERT INTO AFILIADO (RUT,VERIFICADOR,ID_PLAN) VALUES ('16905702','5',5);

INSERT INTO PRESTACION (NOMBRE,CODIGO) VALUES ('Gregory','PRES001');
INSERT INTO PRESTACION (NOMBRE,CODIGO) VALUES ('Aline','PRES002');
INSERT INTO PRESTACION (NOMBRE,CODIGO) VALUES ('Leila','PRES003');
INSERT INTO PRESTACION (NOMBRE,CODIGO) VALUES ('Brady','PRES004');
INSERT INTO PRESTACION (NOMBRE,CODIGO) VALUES ('Hiroko','PRES005');

INSERT INTO BENEFICIO (PORCENTAJE,LIMITE_DINERO,ID_PLAN,ID_PRESTACION) VALUES (90,925518,1,1);
INSERT INTO BENEFICIO (PORCENTAJE,LIMITE_DINERO,ID_PLAN,ID_PRESTACION) VALUES (80,830584,2,2);
INSERT INTO BENEFICIO (PORCENTAJE,LIMITE_DINERO,ID_PLAN,ID_PRESTACION) VALUES (23,554008,3,3);
INSERT INTO BENEFICIO (PORCENTAJE,LIMITE_DINERO,ID_PLAN,ID_PRESTACION) VALUES (53,334737,4,4);
INSERT INTO BENEFICIO (PORCENTAJE,LIMITE_DINERO,ID_PLAN,ID_PRESTACION) VALUES (89,758366,5,5);

commit;