//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheekiBreeki.CMH.Terminal.BL.SeguroServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SeguroRequest", Namespace="http://schemas.datacontract.org/2004/07/Cheekibreeki.CMH.Seguro.WS")]
    [System.SerializableAttribute()]
    public partial class SeguroRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AfiliadoRutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoPrestacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PrecioPrestacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AfiliadoRut {
            get {
                return this.AfiliadoRutField;
            }
            set {
                if ((this.AfiliadoRutField.Equals(value) != true)) {
                    this.AfiliadoRutField = value;
                    this.RaisePropertyChanged("AfiliadoRut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoPrestacion {
            get {
                return this.CodigoPrestacionField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoPrestacionField, value) != true)) {
                    this.CodigoPrestacionField = value;
                    this.RaisePropertyChanged("CodigoPrestacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PrecioPrestacion {
            get {
                return this.PrecioPrestacionField;
            }
            set {
                if ((this.PrecioPrestacionField.Equals(value) != true)) {
                    this.PrecioPrestacionField = value;
                    this.RaisePropertyChanged("PrecioPrestacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SeguroResponse", Namespace="http://schemas.datacontract.org/2004/07/Cheekibreeki.CMH.Seguro.WS")]
    [System.SerializableAttribute()]
    public partial class SeguroResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AfiliadoTieneSeguroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DescuentoPesosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AfiliadoTieneSeguro {
            get {
                return this.AfiliadoTieneSeguroField;
            }
            set {
                if ((this.AfiliadoTieneSeguroField.Equals(value) != true)) {
                    this.AfiliadoTieneSeguroField = value;
                    this.RaisePropertyChanged("AfiliadoTieneSeguro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DescuentoPesos {
            get {
                return this.DescuentoPesosField;
            }
            set {
                if ((this.DescuentoPesosField.Equals(value) != true)) {
                    this.DescuentoPesosField = value;
                    this.RaisePropertyChanged("DescuentoPesos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SeguroServiceReference.ISeguroWS")]
    public interface ISeguroWS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISeguroWS/obtenerBeneficio", ReplyAction="http://tempuri.org/ISeguroWS/obtenerBeneficioResponse")]
        CheekiBreeki.CMH.Terminal.BL.SeguroServiceReference.SeguroResponse obtenerBeneficio(CheekiBreeki.CMH.Terminal.BL.SeguroServiceReference.SeguroRequest seguroRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISeguroWS/obtenerBeneficio", ReplyAction="http://tempuri.org/ISeguroWS/obtenerBeneficioResponse")]
        System.Threading.Tasks.Task<CheekiBreeki.CMH.Terminal.BL.SeguroServiceReference.SeguroResponse> obtenerBeneficioAsync(CheekiBreeki.CMH.Terminal.BL.SeguroServiceReference.SeguroRequest seguroRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISeguroWSChannel : CheekiBreeki.CMH.Terminal.BL.SeguroServiceReference.ISeguroWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SeguroWSClient : System.ServiceModel.ClientBase<CheekiBreeki.CMH.Terminal.BL.SeguroServiceReference.ISeguroWS>, CheekiBreeki.CMH.Terminal.BL.SeguroServiceReference.ISeguroWS {
        
        public SeguroWSClient() {
        }
        
        public SeguroWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SeguroWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SeguroWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SeguroWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CheekiBreeki.CMH.Terminal.BL.SeguroServiceReference.SeguroResponse obtenerBeneficio(CheekiBreeki.CMH.Terminal.BL.SeguroServiceReference.SeguroRequest seguroRequest) {
            return base.Channel.obtenerBeneficio(seguroRequest);
        }
        
        public System.Threading.Tasks.Task<CheekiBreeki.CMH.Terminal.BL.SeguroServiceReference.SeguroResponse> obtenerBeneficioAsync(CheekiBreeki.CMH.Terminal.BL.SeguroServiceReference.SeguroRequest seguroRequest) {
            return base.Channel.obtenerBeneficioAsync(seguroRequest);
        }
    }
}
