//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cheekibreeki.CMH.Seguro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPRESA
    {
        public EMPRESA()
        {
            this.PLAN = new HashSet<PLAN>();
        }
    
        public int ID_EMPRESA { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<int> ID_T_EMPRESA { get; set; }
    
        public virtual T_EMPRESA T_EMPRESA { get; set; }
        public virtual ICollection<PLAN> PLAN { get; set; }
    }
}
