//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cheekibreeki.CMH.Seguro.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SeguroEntities : DbContext
    {
        public SeguroEntities()
            : base("name=SeguroEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AFILIADO> AFILIADO { get; set; }
        public DbSet<BENEFICIO> BENEFICIO { get; set; }
        public DbSet<EMPRESA> EMPRESA { get; set; }
        public DbSet<PLAN> PLAN { get; set; }
        public DbSet<PRESTACION> PRESTACION { get; set; }
        public DbSet<T_EMPRESA> T_EMPRESA { get; set; }
    }
}
