//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cheekibreeki.CMH.Seguro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EMPRESA
    {
        public T_EMPRESA()
        {
            this.EMPRESA = new HashSet<EMPRESA>();
        }
    
        public int ID_T_EMPRESA { get; set; }
        public string NOMBRE { get; set; }
    
        public virtual ICollection<EMPRESA> EMPRESA { get; set; }
    }
}
