//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cheekibreeki.CMH.Seguro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRESTACION
    {
        public PRESTACION()
        {
            this.BENEFICIO = new HashSet<BENEFICIO>();
        }
    
        public int ID_PRESTACION { get; set; }
        public string NOMBRE { get; set; }
        public string CODIGO { get; set; }
    
        public virtual ICollection<BENEFICIO> BENEFICIO { get; set; }
    }
}
