//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheekiBreeki.CMH.Terminal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATENCION_AGENDADA
    {
        public decimal ID_ATENCION_AGENDADA { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<System.DateTime> HORA { get; set; }
        public string OBSERVACIONES { get; set; }
        public Nullable<decimal> ID_PACIENTE { get; set; }
        public Nullable<decimal> ID_PERSONAL_MEDICO { get; set; }
        public Nullable<decimal> ID_PAGO { get; set; }
        public Nullable<decimal> ID_PRESTACION { get; set; }
        public Nullable<decimal> ID_ESTADO_ATENCION { get; set; }
    }
}
