
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CheekiBreeki.CMH.Terminal.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class DIA_SEM
{

    public DIA_SEM()
    {

        this.BLOQUE = new HashSet<BLOQUE>();

    }


    public int ID_DIA { get; set; }

    public string NOMBRE_IDA { get; set; }



    public virtual ICollection<BLOQUE> BLOQUE { get; set; }

}

}
