//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheekiBreeki.CMH.Terminal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTRADA_FICHA
    {
        public int ID_ENTRADA_FICHA { get; set; }
        public string NOMBRE_ENTRADA { get; set; }
        public string CONTENIDO_ENTRADA { get; set; }
        public Nullable<System.DateTime> FECHA_ENTRADA { get; set; }
        public Nullable<int> ID_PACIENTE { get; set; }
        public int ID_TIPO_FICHA { get; set; }
    
        public virtual PACIENTE PACIENTE { get; set; }
        public virtual TIPO_FICHA TIPO_FICHA { get; set; }
    }
}
