//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheekiBreeki.CMH.Terminal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESPECIALIDAD
    {
        public ESPECIALIDAD()
        {
            this.PRESTACION = new HashSet<PRESTACION>();
            this.PERS_MEDICO = new HashSet<PERS_MEDICO>();
        }
    
        public int ID_ESPECIALIDAD { get; set; }
        public string NOM_ESPECIALIDAD { get; set; }
    
        public virtual ICollection<PRESTACION> PRESTACION { get; set; }
        public virtual ICollection<PERS_MEDICO> PERS_MEDICO { get; set; }
    }
}
