//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheekiBreeki.CMH.Terminal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADO_ATEN
    {
        public ESTADO_ATEN()
        {
            this.ATENCION_AGEN = new HashSet<ATENCION_AGEN>();
        }
    
        public int ID_ESTADO_ATEN { get; set; }
        public string NOM_ESTADO_ATEN { get; set; }
    
        public virtual ICollection<ATENCION_AGEN> ATENCION_AGEN { get; set; }
    }
}
