//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheekiBreeki.CMH.Terminal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FICHA
    {
        public FICHA()
        {
            this.ENTRADA_FICHA = new HashSet<ENTRADA_FICHA>();
        }
    
        public int ID_FICHA { get; set; }
        public Nullable<System.DateTime> FEC_NAC { get; set; }
        public string SEXO { get; set; }
        public Nullable<int> ID_PACIENTE { get; set; }
    
        public virtual ICollection<ENTRADA_FICHA> ENTRADA_FICHA { get; set; }
        public virtual PACIENTE PACIENTE { get; set; }
    }
}
