
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CheekiBreeki.CMH.Terminal.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class FUNCIONARIO
{

    public FUNCIONARIO()
    {

        this.CAJA = new HashSet<CAJA>();

    }


    public int ID_FUNCIONARIO { get; set; }

    public int ID_CARGO_FUNCI { get; set; }

    public int ID_PERSONAL { get; set; }



    public virtual ICollection<CAJA> CAJA { get; set; }

    public virtual CARGO CARGO { get; set; }

    public virtual PERSONAL PERSONAL { get; set; }

}

}
