//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheekiBreeki.CMH.Terminal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HORARIO
    {
        public int ID_HORARIO { get; set; }
        public int ID_BLOQUE { get; set; }
        public int ID_PERS_MEDICO { get; set; }
    
        public virtual BLOQUE BLOQUE { get; set; }
        public virtual PERS_MEDICO PERS_MEDICO { get; set; }
    }
}
