//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheekiBreeki.CMH.Terminal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGPAGOHONORARIO
    {
        public int IDLOGPAGOHONORARIO { get; set; }
        public string NOMBRE { get; set; }
        public string BANCO { get; set; }
        public string TIPOCUENTA { get; set; }
        public Nullable<int> CUENTA { get; set; }
        public Nullable<int> SUBTOTAL { get; set; }
        public Nullable<int> TOTAL { get; set; }
        public Nullable<System.DateTime> FECHOR { get; set; }
    }
}
