//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheekiBreeki.CMH.Terminal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGPAGOHONORARIO
    {
        public int IDLOGPAGOHONORARIO { get; set; }
        public Nullable<int> TOTAL { get; set; }
        public Nullable<System.DateTime> FECHOR { get; set; }
        public int ID_CUEN_BANCARIA { get; set; }
    
        public virtual CUEN_BANCARIA CUEN_BANCARIA { get; set; }
    }
}
