//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheekiBreeki.CMH.Terminal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONAL
    {
        public PERSONAL()
        {
            this.FUNCIONARIO = new HashSet<FUNCIONARIO>();
            this.PERS_MEDICO = new HashSet<PERS_MEDICO>();
        }
    
        public int ID_PERSONAL { get; set; }
        public string NOMBRES { get; set; }
        public string APELLIDOS { get; set; }
        public Nullable<int> REMUNERACION { get; set; }
        public string HASHED_PASS { get; set; }
        public Nullable<byte> PORCENT_DESCUENTO { get; set; }
        public string RUT { get; set; }
        public string VERIFICADOR { get; set; }
    
        public virtual ICollection<FUNCIONARIO> FUNCIONARIO { get; set; }
        public virtual ICollection<PERS_MEDICO> PERS_MEDICO { get; set; }
    }
}
