//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheekiBreeki.CMH.Terminal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_EQUIPO
    {
        public TIPO_EQUIPO()
        {
            this.EQUIPO_REQ = new HashSet<EQUIPO_REQ>();
            this.INVENTARIO = new HashSet<INVENTARIO>();
        }
    
        public int ID_TIPO_EQUIPO { get; set; }
        public string NOMBRE_TIPO_EQUIPO { get; set; }
    
        public virtual ICollection<EQUIPO_REQ> EQUIPO_REQ { get; set; }
        public virtual ICollection<INVENTARIO> INVENTARIO { get; set; }
    }
}
