//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheekiBreeki.CMH.Terminal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_C_BANCARIA
    {
        public TIPO_C_BANCARIA()
        {
            this.CUEN_BANCARIA = new HashSet<CUEN_BANCARIA>();
        }
    
        public int ID_TIPO_C_BANCARIA { get; set; }
        public string NOM_C_BANCARIA { get; set; }
    
        public virtual ICollection<CUEN_BANCARIA> CUEN_BANCARIA { get; set; }
    }
}
