//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheekiBreeki.CMH.Terminal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TURNO
    {
        public TURNO()
        {
            this.PERS_MEDICO = new HashSet<PERS_MEDICO>();
        }
    
        public int ID_TURNO { get; set; }
        public Nullable<System.DateTime> HORA_INI { get; set; }
        public Nullable<System.DateTime> HORA_FIN { get; set; }
        public string NOMBRE_TURNO { get; set; }
    
        public virtual ICollection<PERS_MEDICO> PERS_MEDICO { get; set; }
    }
}
