//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheekiBreeki.CMH.Terminal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TURNO
    {
        public int ID_TURNO { get; set; }
        public string NOMBRE_TURNO { get; set; }
        public Nullable<byte> NUMHORA_INI { get; set; }
        public Nullable<byte> NUMMINU_INI { get; set; }
        public Nullable<byte> NUMHORA_FIN { get; set; }
        public Nullable<byte> NUMMINU_FIN { get; set; }
    }
}
